//--------------------------------------------------------------------------------
// Auto-generated by LiteX (c8343879) on 2023-01-12 18:00:51
//--------------------------------------------------------------------------------
#ifndef __GENERATED_MEM_H
#define __GENERATED_MEM_H

#ifndef CSR_BASE
#define CSR_BASE 0x00000000L
#define CSR_SIZE 0x00010000
#endif

#ifndef MEM_REGIONS
#define MEM_REGIONS "CSR  0x00000000 0x10000 "
#endif
#endif
