
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xiic.h"

/*
* The configuration table for devices
*/

XIic_Config XIic_ConfigTable[XPAR_XIIC_NUM_INSTANCES] =
{
	{
		XPAR_I2C_CORES_I2C1_DEVICE_ID,
		XPAR_I2C_CORES_I2C1_BASEADDR,
		XPAR_I2C_CORES_I2C1_TEN_BIT_ADR,
		XPAR_I2C_CORES_I2C1_GPO_WIDTH
	},
	{
		XPAR_I2C_CORES_I2C2_DEVICE_ID,
		XPAR_I2C_CORES_I2C2_BASEADDR,
		XPAR_I2C_CORES_I2C2_TEN_BIT_ADR,
		XPAR_I2C_CORES_I2C2_GPO_WIDTH
	}
};


